services:
  app:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - app_data:/app/apps/api/storage

volumes:
  app_data:
