ALTER TABLE nodes ADD COLUMN warp_endpoint TEXT NOT NULL DEFAULT '';
ALTER TABLE nodes ADD COLUMN argo_status TEXT NOT NULL DEFAULT '';
ALTER TABLE nodes ADD COLUMN argo_domain TEXT NOT NULL DEFAULT '';
ALTER TABLE nodes ADD COLUMN storage_total_bytes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE nodes ADD COLUMN storage_used_bytes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE nodes ADD COLUMN storage_usage_percent REAL;
