ALTER TABLE nodes ADD COLUMN permission_mode TEXT NOT NULL DEFAULT '';
ALTER TABLE nodes ADD COLUMN sing_box_version TEXT NOT NULL DEFAULT '';
ALTER TABLE nodes ADD COLUMN sing_box_status TEXT NOT NULL DEFAULT '';
ALTER TABLE nodes ADD COLUMN xray_version TEXT NOT NULL DEFAULT '';
ALTER TABLE nodes ADD COLUMN xray_status TEXT NOT NULL DEFAULT '';
